#!/bin/bash

# Script de Teste - Event Blocking e Layout
# Testes manuais a serem executados no dispositivo após instalação do APK

echo "🧪 ROTEIRO DE TESTES - EVENT BLOCKING E LAYOUT"
echo "=============================================="
echo ""
echo "📱 APK: android/app/build/outputs/apk/release/app-release.apk"
echo "📊 Tamanho: 3.0MB"
echo ""
echo "Para instalar:"
echo "  adb install -r android/app/build/outputs/apk/release/app-release.apk"
echo ""
echo "=============================================="
echo ""

echo "🎯 TESTE 1: Welcome Page - Input e Botão"
echo "----------------------------------------"
echo "✅ Abrir o app"
echo "✅ Clicar no input de nome"
echo "   → Teclado deve abrir"
echo "   → Input deve permanecer visível"
echo "   → Texto deve ser digitado normalmente"
echo "✅ Digitar um nome"
echo "✅ Fechar teclado"
echo "✅ Clicar no botão 'Iniciar Jornada'"
echo "   → Deve navegar para Home"
echo ""

echo "🎯 TESTE 2: Home Page - Cards Clicáveis"
echo "----------------------------------------"
echo "✅ Verificar se todos os 3 cards estão visíveis"
echo "✅ Clicar no card 'Quiz'"
echo "   → Deve navegar para Quiz"
echo "✅ Voltar (botão back)"
echo "✅ Clicar no card 'Forca'"
echo "   → Deve navegar para Hangman"
echo "✅ Voltar (botão back)"
echo "✅ Clicar no card 'Estatísticas'"
echo "   → Deve navegar para Statistics"
echo "✅ Testar cliques em diferentes áreas dos cards"
echo "   → Canto superior esquerdo"
echo "   → Centro"
echo "   → Canto inferior direito"
echo "   → Todos devem funcionar!"
echo ""

echo "🎯 TESTE 3: Quiz - Options e Keyboard"
echo "----------------------------------------"
echo "✅ Iniciar um quiz"
echo "✅ Clicar em cada alternativa (A, B, C, D)"
echo "   → Deve selecionar e mostrar feedback"
echo "✅ Clicar no botão 'Próxima'"
echo "   → Deve avançar para próxima questão"
echo "✅ Repetir para várias questões"
echo "✅ Verificar se progressbar funciona"
echo ""

echo "🎯 TESTE 4: Hangman - Letras Clicáveis"
echo "----------------------------------------"
echo "✅ Abrir o jogo da forca"
echo "✅ Clicar em várias letras"
echo "   → Letras devem ser marcadas"
echo "   → Boneco deve aparecer gradualmente"
echo "✅ Testar letras nos cantos do teclado virtual"
echo "✅ Testar letras no centro"
echo "✅ Todas devem responder ao clique"
echo ""

echo "🎯 TESTE 5: Statistics - Interação com Keyboard"
echo "------------------------------------------------"
echo "✅ Abrir Statistics"
echo "✅ Se houver inputs, testar foco"
echo "✅ Verificar se teclado não cobre conteúdo importante"
echo "✅ Verificar scroll enquanto teclado está aberto"
echo ""

echo "🎯 TESTE 6: Stress Test - Teclado"
echo "-----------------------------------"
echo "✅ Welcome page"
echo "✅ Abrir teclado (clicar no input)"
echo "✅ Tentar clicar no botão 'Iniciar Jornada' COM teclado aberto"
echo "   → Botão deve estar acessível"
echo "   → Clique deve funcionar"
echo "✅ Fechar teclado manualmente"
echo "✅ Clicar novamente no botão"
echo "   → Deve funcionar normalmente"
echo ""

echo "🎯 TESTE 7: Z-index e Overlays"
echo "--------------------------------"
echo "✅ Em cada tela, verificar se:"
echo "   → Botões estão sempre clicáveis"
echo "   → Inputs aceitam foco"
echo "   → Não há elementos invisíveis bloqueando"
echo "   → Cursor muda para 'pointer' em elementos clicáveis"
echo ""

echo "🎯 TESTE 8: Touch Targets"
echo "--------------------------"
echo "✅ Verificar se todos os botões têm tamanho adequado"
echo "   → Mínimo 44x44px"
echo "✅ Tentar clicar nas bordas dos botões"
echo "   → Deve funcionar"
echo "✅ Tentar clicar em cantos de cards"
echo "   → Deve funcionar"
echo ""

echo "🎯 TESTE 9: Rotação de Tela"
echo "-----------------------------"
echo "✅ Abrir Welcome page"
echo "✅ Rotacionar dispositivo (portrait → landscape)"
echo "✅ Verificar se layout se ajusta"
echo "✅ Clicar no input"
echo "   → Teclado deve abrir corretamente"
echo "✅ Voltar para portrait"
echo "✅ Verificar se tudo ainda funciona"
echo ""

echo "🎯 TESTE 10: Navegação Rápida"
echo "------------------------------"
echo "✅ Navegar rapidamente entre telas:"
echo "   Welcome → Home → Quiz → Back → Hangman → Back → Stats → Back"
echo "✅ Verificar se não há elementos travados"
echo "✅ Verificar se não há overlays bloqueando"
echo ""

echo "=============================================="
echo ""
echo "📝 CHECKLIST DE VALIDAÇÃO"
echo "-------------------------"
echo "[ ] Todos os inputs são clicáveis"
echo "[ ] Todos os botões são clicáveis"
echo "[ ] Cards navegam corretamente"
echo "[ ] Teclado não bloqueia elementos importantes"
echo "[ ] Não há elementos invisíveis bloqueando"
echo "[ ] Touch targets têm tamanho adequado"
echo "[ ] Cursor muda para pointer em elementos clicáveis"
echo "[ ] Elementos disabled não aceitam cliques"
echo "[ ] Rotação de tela funciona corretamente"
echo "[ ] Navegação rápida não causa problemas"
echo ""

echo "=============================================="
echo ""
echo "🔧 DEBUG COM CHROME DEVTOOLS"
echo "----------------------------"
echo "1. Conectar dispositivo via USB"
echo "2. Habilitar depuração USB"
echo "3. Abrir Chrome e navegar para: chrome://inspect"
echo "4. Selecionar o app 'Formadora IV'"
echo "5. Abrir DevTools"
echo "6. Executar no console:"
echo ""
echo "// Verificar elemento em ponto de clique"
echo "document.addEventListener('click', function(e) {"
echo "  console.log('Clicked:', e.target);"
echo "  console.log('Z-index:', window.getComputedStyle(e.target).zIndex);"
echo "  console.log('Pointer events:', window.getComputedStyle(e.target).pointerEvents);"
echo "}, true);"
echo ""
echo "// Testar se elemento está bloqueado"
echo "function checkBlocking(selector) {"
echo "  const el = document.querySelector(selector);"
echo "  const rect = el.getBoundingClientRect();"
echo "  const center = document.elementFromPoint("
echo "    rect.left + rect.width / 2,"
echo "    rect.top + rect.height / 2"
echo "  );"
echo "  if (center !== el) {"
echo "    console.warn('BLOQUEADO por:', center);"
echo "  } else {"
echo "    console.log('✅ Clicável');"
echo "  }"
echo "}"
echo ""
echo "// Uso"
echo "checkBlocking('ion-input');"
echo "checkBlocking('.menu-card');"
echo "checkBlocking('.option-card');"
echo ""

echo "=============================================="
echo ""
echo "📊 RESULTADOS ESPERADOS"
echo "-----------------------"
echo "✅ TODOS os testes devem passar"
echo "✅ Nenhum elemento deve estar bloqueado"
echo "✅ Teclado não deve causar problemas de layout"
echo "✅ Z-index deve estar corretamente configurado"
echo "✅ Pointer events devem funcionar em todos os elementos"
echo ""

echo "=============================================="
echo ""
echo "⚠️  SE ALGUM TESTE FALHAR"
echo "------------------------"
echo "1. Anotar qual teste falhou"
echo "2. Anotar qual elemento não está funcionando"
echo "3. Usar Chrome DevTools para investigar:"
echo "   - Z-index do elemento"
echo "   - Pointer events do elemento"
echo "   - Elemento que está no ponto de clique"
echo "4. Verificar no código correspondente:"
echo "   - src/app/[página]/[página].page.scss"
echo "   - src/global.scss"
echo "5. Ajustar z-index ou pointer-events conforme necessário"
echo ""

echo "=============================================="
echo "✅ Testes concluídos!"
echo "=============================================="

