import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  home,
  statsChart,
  statsChartOutline,
  school,
  schoolOutline,
  gameController,
  gameControllerOutline,
  person,
  trophy,
  trendingUp,
  checkbox,
  analytics,
  time,
  play,
  trash,
  closeCircle,
  closeCircleOutline,
  flash,
  star,
  flame,
  ribbon,
  folder,
  close,
  checkmarkCircle,
  helpCircle,
  refresh,
  shareSocial,
  swapHorizontal,
  swapHorizontalOutline,
  bulb,
  arrowBack,
  send,
  arrowForward,
  happy,
  shieldCheckmark,
  shieldCheckmarkOutline,
  bookOutline,
  documentTextOutline,
  peopleOutline,
  leafOutline,
  lockClosedOutline,
  newspaperOutline,
  rocketOutline,
} from 'ionicons/icons';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

// Registrar todos os ícones usados no aplicativo
addIcons({
  'home': home,
  'stats-chart': statsChart,
  'stats-chart-outline': statsChartOutline,
  'school': school,
  'school-outline': schoolOutline,
  'game-controller': gameController,
  'game-controller-outline': gameControllerOutline,
  'person': person,
  'trophy': trophy,
  'trending-up': trendingUp,
  'checkbox': checkbox,
  'analytics': analytics,
  'time': time,
  'play': play,
  'trash': trash,
  'close-circle': closeCircle,
  'close-circle-outline': closeCircleOutline,
  'flash': flash,
  'star': star,
  'flame': flame,
  'ribbon': ribbon,
  'folder': folder,
  'close': close,
  'checkmark-circle': checkmarkCircle,
  'help-circle': helpCircle,
  'refresh': refresh,
  'share-social': shareSocial,
  'swap-horizontal': swapHorizontal,
  'swap-horizontal-outline': swapHorizontalOutline,
  'bulb': bulb,
  'arrow-back': arrowBack,
  'send': send,
  'arrow-forward': arrowForward,
  'happy': happy,
  'shield-checkmark': shieldCheckmark,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'book-outline': bookOutline,
  'document-text-outline': documentTextOutline,
  'people-outline': peopleOutline,
  'leaf-outline': leafOutline,
  'lock-closed-outline': lockClosedOutline,
  'newspaper-outline': newspaperOutline,
  'rocket-outline': rocketOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular({
      mode: 'md'
    }),
    provideRouter(routes, withPreloading(PreloadAllModules)),
  ],
});
